### ISSUE TITLE
Some preferences are not true or false anymore

### ISSUE THREAD

**Issue by 0xsyr0** [K3V1991/Disable-Firefox-Telemetry-and-Data-Collection#2]
The following preferences now requires Boolean, Number or String.

| Preference | Value |
| --- | --- |
| datareporting.healthreport.service.enabled | Boolean, Number or String |
| datareporting.sessions.current.clean | Boolean, Number or String |
| devtools.onboarding.telemetry.logged | Boolean, Number or String |
| toolkit.telemetry.hybridContent.enabled | Boolean, Number or String |
| toolkit.telemetry.rejected | Boolean, Number or String |
| toolkit.telemetry.unifiedIsOptIn | Boolean, Number or String |

**Comment by ghost** [comment]
https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/obsolete/index.html
