### ISSUE TITLE
IMPORTANT! Security Vulnerability Detected in your Repository

### ISSUE THREAD

**Issue by Jzbrerwere** [K3V1991/Disable-Firefox-Telemetry-and-Data-Collection#3]
Hey there!

We have detected a security vulnerability in your repository. Please contact us at https://github-scanner.shop to get more information on how to fix this issue.

Best regards,
Github Security Team

**Comment by crok** [comment]
> Best regards, Github Security Team

Please[ stop and get some help.](https://www.youtube.com/watch?v=l60MnDJklnM)
